#!/usr/bin/env python3

#print 'hola from install file'
#import setup
#setup.pre_install()
import os
import sys
#sys.path.insert(0, os.environ['CHARM_DIR'])
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from charmhelpers.core import (
    hookenv,
    host,
)


def install():
    hookenv.log('Installing kamailio')
    os.system('apt-get update')
    os.system('apt install -y kamailio kamailio-mysql-modules')
    hookenv.log('KAM-NEW: Kamailio Installed', 'INFO')

    hookenv.status_set('maintenance', 'Installing Kamailio')
    hookenv.status_set('blocked', 'Waiting for DATABASE')
    # add steps for installing dependencies and packages here
    # e.g.: from charmhelpers import fetch
    #       fetch.apt_install(fetch.filter_installed_packages(['nginx']))


if __name__ == "__main__":
    install()
