#!/usr/bin/env python3

import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from charmhelpers.core import (
    hookenv,
    host,
)


def start():
        hookenv.log('Hello Juju log Start hook')
        pass
